# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://arch-ive.github.io/Seasoned-Recipes/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = true
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  cuisine = "cuisines" 

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]