# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Everything"
  pageRef = "recipes/all"
  weight = 1

[[main]]
  name = "Seasons"
  pageRef = "seasons/"
  weight = 3

[[main]]
  name = "Main Meals"
  pageRef = "recipe/main"
  weight = 2

[[main]]
  name = "Chicken"
  parent = "Hero Ingredient"
  pageRef = "heros/Chicken"
  weight = 5

[[main]]
  name = "Beef"
  parent = "Hero Ingredient"
  pageRef = "heros/Beef"
  weight = 6

[[main]]
  name = "Lamb"
  parent = "Hero Ingredient"
  pageRef = "heros/Lamb"
  weight = 7

[[main]]
  name = "Pork"
  parent = "Hero Ingredient"
  pageRef = "heros/Pork"
  weight = 8

[[main]]
  name = "Fish"
  parent = "Hero Ingredient"
  pageRef = "heros/Fish"
  weight = 9

[[main]]
  name = "Pasta"
  parent = "Hero Ingredient"
  pageRef = "heros/Pasta"
  weight = 10

[[main]]
  name = "Vege"
  parent = "Hero Ingredient"
  pageRef = "heros/Vege"
  weight = 11

[[main]]
  name = "Sweet"
  pageRef = "recipe/sweet"
  weight = 4

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
