name: Build Theme

on:
  push:
    branches:
      - master
  pull_request:

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "${{ github.head_ref }}"
      - name: Install dependencies and Build Theme
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run assets
      - name: Commit and push Chart.js changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/lib/chart/*"
          commit_message: "📦 Update packaged ChartJS"
      - name: Commit Fuse changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/lib/fuse/*"
          commit_message: "📦 Update packaged FuseJS"
      - name: Commit KaTeX changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/lib/katex/*"
          commit_message: "📦 Update packaged KaTeX"
      - run: npm run gh-page-compile
      - name: Commit CSS changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/css/compiled/main.css"
          commit_message: "💄 Rebuild CSS"
      - run: git push