# Workflow for building and deploying a Hugo site to GitHub Pages
name: Build & Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies and Build Theme
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run assets
      - name: Commit and push Chart.js changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/lib/chart/*"
          commit_message: "📦 Update packaged ChartJS"
      - name: Commit Fuse changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/lib/fuse/*"
          commit_message: "📦 Update packaged FuseJS"
      - name: Commit KaTeX changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/lib/katex/*"
          commit_message: "📦 Update packaged KaTeX"
      - run: npm run build
      - name: Commit CSS changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "${{ github.head_ref }}"
          push_options: "--dry-run"
          file_pattern: "assets/css/compiled/main.css"
          commit_message: "💄 Rebuild CSS"
      - run: git push
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: https://Arch-ive.github.io/Seasoned-Recipes/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2